### ISSUE TITLE
Cannot build on archlinux with gcc 7.2.0

### ISSUE THREAD

**Issue by luntik2012** [EIPStackGroup/OpENer#111]
got some error meaning RESTRICT keyword not found.
edited OpENer_PLATFORM_INCLUDES.cmake
in buildsupport/POSIX to this:
`add_definitions(-DRESTRICT=)`
instead of "if".
it works now

**Comment by CapXilinx** [comment]
That's strange, as restrict, to which the RESTRICT definition should resolve, is a valid C keyword, and the if works for me and for the TravisCI.
What are your CMake settings?

**Comment by CapXilinx** [comment]
Oh, I see I always added C++ support for the testing framework, pure C make fails, as RESTRICT is never resolved to restrict

**Comment by luntik2012** [comment]
all right. works now
