### ISSUE TITLE
is it necessary to use cmake >= 3.7.2?

### ISSUE THREAD

**Issue by luntik2012** [EIPStackGroup/OpENer#113]
I cannot build OpENer in Ubuntu 16.04 after cloning because you require cmake version >= 3.7.2 (while Ubuntu 16.04 has 3.5.1 for now).
But changing to `cmake_minimum_required( VERSION 3.5.1 )` helps, I can build it.

**Comment by CapXilinx** [comment]
If 3.5.1 is working, than it is ok for me. I just could not find out, which version is needed for IN_LIST

**Comment by CapXilinx** [comment]
And Gentoo already supports 3.7.2 ;)

**Comment by simonlui** [comment]
Hi,

Seems like IN_LIST was introduced in 3.3, but unfortunately, I don't have a machine with that old of a cmake version.

https://cmake.org/cmake/help/v3.3/policy/CMP0057.html

**Comment by CapXilinx** [comment]
Hi,
thanks! I will check and update the cmake file accordingly

**Comment by CapXilinx** [comment]
Fixed in commit 48111f37ebf309897061424fec35acb9e7d03738
