### ISSUE TITLE
Queries: OpENer with Allen-Bradley PLC

### ISSUE THREAD

**Issue by shakthimaan** [EIPStackGroup/OpENer#14]
#1 Does this implementation also support ControlNet, DeviceNet in addition to the Ethernet/IP stack?
#2 What do 'ip address' and 'hostaddress' in the OpeNER command line tool correspond to?
#3 Are there any example configurations that I can try with an Allen-Bradley PLC?

**Comment by Bolkano** [comment]
Hi, 
Does your project could be used for example for a custom HMI connected (Ethernet/IP) with an Allen-Bradley PLC?

**Comment by azoitl** [comment]
Hi,

in principle yes. However OpENer is only an EtherNet/IP adpater devices (i.e., Slave) for HMIs this may not be the best solution. You may want to look for an EtherNet/IP stack which is able to act as explicit message client. This is currently not possible with OpENer.

**Comment by vmakwana** [comment]
I could not completely understand what you said.

Do you mean OpENer acts as a slave?

If yes, does it mean that we cannot read/write data from/to an A-B PLC?

Okay before we get confused more, please answer the following question:
Can I use OpENer to read data from and write data to an Allen-Bradley PLC?
Thanks.

-Vikrant

**Comment by azoitl** [comment]
Sorry for the confusing answer. I tried to use EtherNet/IP terms so that you can align it to other solutions.

Yes OpENer can only act as slave. So a PLC can read and write values to an OpENer device. However a OpENer device can not actively read or write to a PLC. Therefore I don't think that OpENer is perfectly suited for you.

**Comment by Bolkano** [comment]
Thank you for your answer. So we can say that OpENer is a Class 3 messaging Server which is suitable for producing hardware devices that support Ethernet/IP. And it's not suitable for HMI/SCADA solutions.

**Comment by azoitl** [comment]
in addition to Class 3 messaging Server it is also a Class 1 server for implicit I/O messages. But yes it is not suitable for HMI/SCADA. 
There have been some libraries available providing EIP support for HMI/SCADA but AFAIK none if it is open source any more. From what I know the code in OpENer could help you to implement such a lib.
