### ISSUE TITLE
Can you provide a client example for reference?

### ISSUE THREAD

**Issue by SmartPointer1** [EIPStackGroup/OpENer#158]
Hello,
    Can you provide a client example for reference?

**Comment by CapXilinx** [comment]
Hi,

could you specify what you would expect as a client reference example?

**Comment by SmartPointer1** [comment]
Hi，
I want an example that can get device information or other information.

**Comment by CapXilinx** [comment]
OpENer has not the goal to provide that kind of functionality, as it is a stack for adapter devices (explicit and implicit messaging server). If you want to try it out, you can either use the Molex ENIP tool, or you can take a look at the ENIP explorer at Sourceforge
