### ISSUE TITLE
Could you include a Cmake startup description

### ISSUE THREAD

**Issue by jkvatne** [EIPStackGroup/OpENer#162]
Could you extend the Readme file with a better description on how to use Cmake to configure the sample application on both linux and windows?  A complete step-by-step description on how to make an executable for the sample application would be very nice.  It would have saved me a lot of work.  I use Cygwin, but the readme only says "Invoke setup_windows.bat or configure via CMake", none of which I could get to work.

Also a description on how to find the adapter index would be nice (on windows). I had to write a program to find it, but I am sure there is a simpler way. It would also be better to use the local IP address in search of the adapter to use, as this is more often known.

**Comment by CapXilinx** [comment]
Hi,
thanks for the input. You can easily find the correct adapter index on Windows via the command "route print". If you want to provide the functionality for Windows to get the correct adapter via the IP address, I am happy to merge a pull request.

For the CMake description, I will try to come up with a better description as soon as I have some time for that

Best regards,
Martin
