### ISSUE TITLE
A basic question about OpENer

### ISSUE THREAD

**Issue by alexhjf** [EIPStackGroup/OpENer#164]
Hi,
I'm a new developer of EIP, I want to know that if OpENer could be implemented to be a explicit message server and client ? Or it's just an I/O adapter ?
Thank you!

**Comment by azoitl** [comment]
as an I/O adapter requires an Explicit message server OpENer is automatically also an explicit message server and you can set it up quite easily. Theoretically much code in OpENer can also be utilized for explicit message clients. But for these much more work has to be done (e.g., code for connecting to severs, assembling requests, processing responses).

**Comment by alexhjf** [comment]
Hi, azoitl
Yeah I've learned that from reading "_A Guide for Ethernet/IP Developers_" of _ODVA_ .
So just like a typical EIP adapter, OpENer has the functionality of Unconnected message Server/Client, Connected message Server and I/O Server. Am I right ?

**Comment by CapXilinx** [comment]
Hi,
no a typical EIP adapter is an implicit and explicit connection server without any client capabilites. Connected or unconnected messages are only two types of explicit connections. Unconnected message do not establish a CIP connection before sendings commands.

OpENer could still serve as a base for a CIP client, as most of the message structures and the functionality for encoding messages are available for further use.
