### ISSUE TITLE
Compile error C2371 in VS 2017/Windows10

### ISSUE THREAD

**Issue by FalkHaehle** [EIPStackGroup/OpENer#176]
The solution does not compile as the return value `void` is not defined in `CipIdentitySetExtendedDeviceStatus` (Error C2371)

https://github.com/EIPStackGroup/OpENer/blob/3e1de6927e9e565138606da03a6d34123e5b4962/source/src/cip/cipidentity.c#L185

**Comment by CapXilinx** [comment]
Thanks!

I will fix that asap, I have been sick and my laptop broke.

Thanks again and best regards,
Martin
