### ISSUE TITLE
Build fails on Cygwin

### ISSUE THREAD

**Issue by thiagoralves** [EIPStackGroup/OpENer#179]
Running ./setup_posix.sh works. However, after running "make" the compilations ends at 86% with a header missing: ~/OpENer/source/src/ports/POSIX/networkconfig.c:19:10: fatal error: linux/if.h: No such file or directory #include <linux/if.h>

I figured that this file on Cygwin is located at <net/if.h>. After making the change in networkconfig.c, compilation fails again at 97% with another header missing: ~/OpENer/source/src/ports/POSIX/main.c:9:10: fatal error: sys/capability.h: No such file or directory #include <sys/capability.h>

I couldn't find this capability.h header anywhere on the Cygwin include files.

**Comment by isaoparra** [comment]
I have a similar problem on ubuntu 16.04.  it was solved after installing _libcap-dev_

`sudo apt-get install libcap-dev
`

**Comment by thiagoralves** [comment]
I saw that when I was googling about this issue. The problem is that libcap-dev is not available for Cygwin. At least I couldn't find it anywhere on the package list

**Comment by CapXilinx** [comment]
Hi,
I updated the README regarding this issue, but as two alternatives are provided for Windows, and this would need another config switch in CMake I decided against adding a permanent fix to the code.

If this is really an issue for several people out there, we can discuss this again.

Best regards,
Martin
