### ISSUE TITLE
Issues with delay timeout for ListIdentity reply

### ISSUE THREAD

**Issue by SharifuddinAmin** [EIPStackGroup/OpENer#180]
Found following issues with ListIdentity delay timeout.

1. Delay time computation returns 0 most of the time.
Observed that the delay time computation is implemented as below in OpENer code.
delayed_message_buffer->time_out = (maximum_delay_time * rand() ) / RAND_MAX;
The output will not be random as most of the cases the output will be 0, only in case when rand() returns random number in with value similar to RAND_MAX which is huge value, the computed delay timeout will be non zero.
Hence, there would be very little standard deviation of the output random values.

2. Computed delay timeout is used and ListIdentity response is sent immediately
Just to add one more observation related to delay-timeout. 
It seems that delay computations are not getting into effect as the listIdentity response is getting sent immediately.

Summarizing the code flow as below:
1. CheckAndHandleUdpGlobalBroadcastSocket() handles the message reception on broadcast socket
2. It Calls HandleReceivedExplictUdpData() when ListIdentity response is received on broadcast socket, address of outgoing_message is passed.
   2.1. HandleReceivedListIdentityCommandUdp is called with outgoing_message pointer
          2.1.1 This function calls DetermineDelayTime to compute delay time
          2.1.2  EncapsulateListIdentityResponseMessage is with outgoing_message pointer
                   2.1.2.1 This function packs the ListIdentity response
                   2.1.2.2 outgoing_message->used_message_length is updated during ListIdentity response packing.
   2.2. Returns outgoing_message->used_message_length which has now updated in step 2.1.2.2 (i.e. is now > 0)
3  Return value is captured in reply_length which will be > 0
4. Sends packed outgoing_message on socket. i.e. it doesn't matter, whatever the delay is configured, reply is sent immediately.

I also checked the same in old OpENer code v1.2.0. In old code encapsulateListIdentyResponseMessage was getting called with 
the delayed message buffer and hence the response is sent as per computed delay from manageEncapsulationMessages
In latest OpENer manageEncapsulationMessages is just sending junk data while response has already been sent

**Comment by CapXilinx** [comment]
Fixed with PR #182 - best thanks for contribting @SharifuddinAmin
