### ISSUE TITLE
Memory double-free in multi-instance classes

### ISSUE THREAD

**Issue by SharifuddinAmin** [EIPStackGroup/OpENer#185]
In case there are multiple instances of a class, memory for all instances is allocated in one go.
Memory Allocation for Instances:
1. CreateCipClass : Is called during class initialization with number_of_instances > 1
2. AddCipInstances : CreateCipClass calls this function with same number_of_instances
2a. This function allocates memory for all instances
  CipInstance *current_instance = (CipInstance *) CipCalloc(
    number_of_instances, sizeof(CipInstance) );                    /* allocate a block of memory for all created instances*/

Memory Free for Instances:
1. DeleteAllClasses : This function is called to perform cleanup
2. This function loops through all instances and tries to free the memory for each instance !!

Since one memory block was allocated, the whole block would be freed in first iteration of the loop, second iteration onwards it will be a double free and may crash!

**Comment by CapXilinx** [comment]
Should be fixed with PR #194 by AviDeepMidha.
Thanks again!
