### ISSUE TITLE
How to use EtherNet/IP Tool to the sync I/O Module in OpENer?

### ISSUE THREAD

**Issue by Farewellly** [EIPStackGroup/OpENer#197]
I am a new to EtherNet/IP.Now, i use the etherNet/IP Tool to connect the OpENer in Linux. I am using (Process Data) function but it doesn't works.The CIP status show (INVALID SEGMENT IN CONNECTION PATH).
like this:
![image](https://user-images.githubusercontent.com/20672335/58602507-d0812600-82bf-11e9-9bfc-11e0d222c77c.png)
who can give me a hand to figure it out? N.0.1 BG @CapXilinx

**Comment by CapXilinx** [comment]
Hi,
as the error indicates your connection path is wrong. IO connection paths are non-trivial so it took me some time to get one to work (at the end I copied one from the CT tool)

So a correct IO connection path looks like this
200424972C962C64
where
2004 is the assembly class code
2497 - the configuration instance
2C96 - O->T connection point
2C64 - T->O connection point

Best,
Martin

**Comment by CapXilinx** [comment]
As there was no further activity here, I close this issue
