### ISSUE TITLE
arduino support?

### ISSUE THREAD

**Issue by yanzixiang** [EIPStackGroup/OpENer#198]
Is there any plan to support arduino ?

**Comment by CapXilinx** [comment]
No, there is no plan for that, but we are working on a STM32 FreeRTOS version.

Best,
Martin

**Comment by yanzixiang** [comment]
> No, there is no plan for that, but we are working on a STM32 FreeRTOS version.
> 
> Best,
> Martin

It is NOT publised ?

**Comment by CapXilinx** [comment]
Yes, as we are currently working on the base setup and nothing is working right now.

**Comment by yanzixiang** [comment]
https://github.com/espressif/arduino-esp32

recommand this,
this is much more cheaper and easier to use.

https://github.com/espressif/arduino-esp32/blob/master/libraries/AsyncUDP/examples/AsyncUDPServer/AsyncUDPServer.ino

**Comment by crNewton** [comment]
> Yes, as we are currently working on the base setup and nothing is working right now.

I assume MCU support has been abandoned? 
Can I find the effort that has been done toward the STM32 FreeRTOS (or any other MCU) anywhere?
