### ISSUE TITLE
Compilation on linux failed without libcap package

### ISSUE THREAD

**Issue by mlaski** [EIPStackGroup/OpENer#206]
I got error during installation:

`[ 97%] Building C object src/ports/POSIX/CMakeFiles/OpENer.dir/main.c.o
[***]code/OpENer/source/src/ports/POSIX/main.c:9:10: fatal error: sys/capability.h: No such file or directory
 #include <sys/capability.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
`

And this resolves issue:
`sudo apt-get install libcap-dev`

**Comment by CapXilinx** [comment]
Hi,
thanks for the hint, I will add this to the readme.
Best
Martin
