### ISSUE TITLE
wrong device type ?

### ISSUE THREAD

**Issue by yanzixiang** [EIPStackGroup/OpENer#223]
![](https://github.com/yanzixiang/yanzixiang.github.io/raw/master/wrongdevice.PNG)

I want to use OpENer with an Omron PLC which supports EIP,
and got this error,
I think there is some problem witch the default EDS,
but I don't know where should be corrected,
please help

**Comment by stm-at-esd** [comment]
Hi,

looking at the EDS here on GitHub (current state) you have in the [Device] section a device type of "12" i. e. "Communications Adapter" and a revision of 2.3 (i. e. "MajRev = 2" / "MinRev = 3").

Try to send a "ListIdentity" command to your device and see what it responds. Or have a Wireshark log of the conversation between the Omron device and your device and look for "ListIdentity" responses.

On the other hand you should know what you've compiled in.

Make sure that the EDS file installed in the Omron programming IDE for the PLC matches the one you're looking at and your device.

Maybe that helps,
    Stefan

**Comment by CapXilinx** [comment]
Hi,

i checked it right now with my compiled versio of OpENer, device type and version is exactly as @stm-at-esd wrote, and are the same as in the current EDS file.

Best way to check your settings is, as @stm-at-esd suggested, to send a ListIdentity request to check your OpENer. You can do this e.g., with the Molex ENIP tool.

Best regards,
Martin

**Comment by CapXilinx** [comment]
I guess this is resolved?

**Comment by yanzixiang** [comment]
yes,thanks.
