### ISSUE TITLE
What does PIT(ProductionInhibitTime) mean ?

### ISSUE THREAD

**Issue by yanzixiang** [EIPStackGroup/OpENer#224]
20:17:21.254 -> [E][generic_networkhandler.c:612] HandleDataOnTcpSocket(): Entering HandleDataOnTcpSocket for socket: 57
20:17:21.254 -> [E][generic_networkhandler.c:742] HandleDataOnTcpSocket(): Data received on tcp:
20:17:21.254 -> [E][encap.c:158] HandleReceivedExplictTcpData(): Handles data for TCP socket: 57
20:17:21.254 -> [E][encap.c:214] HandleReceivedExplictTcpData(): Send Request/Reply Data
20:17:21.254 -> [E][cipmessagerouter.c:182] NotifyMessageRouter(): NotifyMessageRouter: routing unconnected message
20:17:21.322 -> [E][cipmessagerouter.c:218] NotifyMessageRouter(): NotifyMessageRouter: calling notify function of class 'connection manager'
20:17:21.322 -> [E][cipcommon.c:88] NotifyClass(): notify: found instance 1
20:17:21.322 -> [E][cipcommon.c:99] NotifyClass(): notify: calling ForwardOpen service
20:17:21.322 -> [E][cipconnectionobject.c:215] ConnectionObjectSetState(): ConnectionObjectSetState
20:17:21.322 -> [E][cipconnectionobject.c:157] ConnectionObjectInitializeFromMessage(): ForwardOpen: ConConnID 0, ProdConnID 0, ConnSerNo 271
20:17:21.322 -> [E][cipconnectionmanager.c:539] ForwardOpen(): We have a Non-Null request
20:17:21.356 -> [E][cipconnectionmanager.c:548] ForwardOpen(): We have a Non-Matching request
20:17:21.356 -> [E][cipconnectionmanager.c:1116] ParseConnectionPath(): key: ven ID 152, dev type 145, prod code 18, major 1, minor 1
20:17:21.356 -> [E][cipconnectionmanager.c:1174] ParseConnectionPath(): classid 4 (assembly)
20:17:21.356 -> 
20:17:21.356 -> [E][cipconnectionmanager.c:1189] ParseConnectionPath(): Configuration instance id 151
20:17:21.356 -> [E][cipconnectionmanager.c:1276] ParseConnectionPath(): assembly: type bidirectional
20:17:21.391 -> [E][cipconnectionmanager.c:1300] ParseConnectionPath(): connection point 150
20:17:21.391 -> [E][cipconnectionmanager.c:1300] ParseConnectionPath(): connection point 100
### 20:17:21.391 -> [E][cipconnectionmanager.c:1379] ParseConnectionPath(): Resulting PIT value: 256
20:17:21.391 -> [E][cipioconnection.c:280] EstablishIoConnection(): EstablishIoConnection
20:17:21.391 -> [E][appcontype.c:167] GetIoConnectionForConnectionData(): IO Exclusive Owner connection requested
### 20:17:21.458 -> [E][cipconnectionmanager.c:774] AssembleForwardOpenResponse(): AssembleForwardOpenResponse: sending error response
20:17:21.458 -> [E][cipconnectionobject.c:215] ConnectionObjectSetState(): ConnectionObjectSetState
20:17:21.458 -> [E][cipmessagerouter.c:237] NotifyMessageRouter(): notifyMR: notify function of class 'connection manager' returned a reply
20:17:21.458 -> [E][socket_timer.c:21] SocketTimerSetLastUpdate(): Sets time stamp for socket 57
20:17:21.458 -> [E][generic_networkhandler.c:780] HandleDataOnTcpSocket(): TCP reply sent:
20:17:21.458 -> [E][socket_timer.c:21] SocketTimerSetLastUpdate(): Sets time stamp for socket 57
20:17:21.458 -> [E][generic_networkhandler.c:405] NetworkHandlerProcessOnce(): Socket Loop done

in [cipconnectionmanager.c](https://github.com/EIPStackGroup/OpENer/blob/f76f479b17c7a700d7f832612cc9064be091f005/source/src/cip/cipconnectionmanager.c#L1050)
### ParseConnectionPath() 
```c
EipUint8 ParseConnectionPath(
  CipConnectionObject *connection_object,
  CipMessageRouterRequest *message_router_request,
  EipUint16 *extended_error
  ) {
  const EipUint8 *message = message_router_request->data;
  const size_t connection_path_size = GetSintFromMessage(&message); /* length in words */
  size_t remaining_path = connection_path_size;
  CipClass *class = NULL;

  CipDword class_id = 0x0;
  CipDword instance_id = 0x0;

  /* with 256 we mark that we haven't got a PIT segment */
  ConnectionObjectSetProductionInhibitTime(connection_object, 256);
```

Does this have some relations to this TODO ?
### [TODO](https://github.com/EIPStackGroup/OpENer/blob/f76f479b17c7a700d7f832612cc9064be091f005/source/src/cip/cipconnectionmanager.c#L1134)
```c
//TODO: Refactor this afterwards
    if ( kConnectionObjectTransportClassTriggerProductionTriggerCyclic
         != ConnectionObjectGetTransportClassTriggerProductionTrigger(
           connection_object) ) {
      /*non cyclic connections may have a production inhibit */
      if ( kSegmentTypeNetworkSegment == GetPathSegmentType(message) ) {
        NetworkSegmentSubtype network_segment_subtype =
          GetPathNetworkSegmentSubtype(message);
        if (kNetworkSegmentSubtypeProductionInhibitTimeInMilliseconds
            == network_segment_subtype) {
          OPENER_TRACE_INFO("PIT segment available - value: %u\n",message[1]);
          connection_object->production_inhibit_time = message[1];
          message += 2;
          remaining_path -= 1;
        }
      }
    }
```

**Comment by azoitl** [comment]
Hi,

the PIT is a timer for application triggered or change of state connection the PIT defines the minimal time between to message productions.

BR,
Alois

**Comment by CapXilinx** [comment]
The TODO just says, that this working code should be improved for maintainability and readability.
As the question has been answered I close this issue now.
