### ISSUE TITLE
Some minor cleanup patches and a fix for a flaw in the QoS DSCP handling

### ISSUE THREAD

**Issue by stm-at-esd** [EIPStackGroup/OpENer#259]
Hi,

I would like to publish some minor patches for cleanup and a small fix for the QoS object.

Here  is the patch archive:
[patches_190911.tar.gz](https://github.com/EIPStackGroup/OpENer/files/3601596/patches_190911.tar.gz)

The patch description follows:

1. This patch removes from POSIX/OpENer_PLATFORM_INCLUDES.cmake some compiler 
   defines that are internal (i.e. private) macros from <features.h>. Now the official / public
   _GNU_SOURCE define is used.
   This change also lets us get rid of the Linux specific header <linux/if.h> that was used in 
   networkconfig.c. Now including <net/if.h> suffices.
2. Cleanup: Object's class ids get same type and naming convention
   Object class ids were not declared in a uniform way in the object source headers. This fixes
   also a signed / unsigned mismatch warning.
3. Fix: QoS DSCP values should come into effect only after a restart
   IO connections used the DSCP values effective at the moment when the connection is 
   established. That could be a value already changed after boot-up by an explicit request. But 
   they should use the DSCP value active at boot-up. See Vol. 2, Section "5-7.4.2 DSCP Value 
   Attributes" at the end of the section.
4. Cleanup: Avoid warnings in POSIX/networkconfig.c
  See patch commit message.

I hope you like these patches and apply them to the OpENer tree. Only to avoid that they will
be forgotten I would like to remind you that for the bug report #214 I provided also three cleanup
patches (together with a proposed solution). I would like to have these three patches applied to the tree, also.

Best regards,
    Stefan

**Comment by CapXilinx** [comment]
Hi,
Thanks again! I have not forgotten your patches, I had some troubles last week, so I was unable to take a look at them and merge them into the repository. I will do that asap.

Best regards,
Martin
