### ISSUE TITLE
Integrate a simple EIP Scanner

### ISSUE THREAD

**Issue by timoc** [EIPStackGroup/OpENer#270]
There is an open scanner, but it was buried in another open project abandoned years ago. Someone else seems to have had the same idea about pulling it out to see how useful it is. 

so Here is a simple "scanner" implementation to integrate, or possibly use as reference:
https://github.com/nismoryco/tuxeip

**Comment by CapXilinx** [comment]
Hi,

thanks for the hint, but unfortunately the applied GPLv2 license from the original tuxeip project is incompatible with OpENer's modified BSD license. So any development has to be done from scratch, in order to not violate licenses.

Best regards,
Martin

**Comment by timoc** [comment]
What about this one - it's BSD.
https://github.com/ros-drivers/odva_ethernetip

**Comment by timoc** [comment]
This one is 'Adapted BSD'
https://github.com/liftoff-sr/CIPster

**Comment by azoitl** [comment]
CIPster is OpENer based.

**Comment by CapXilinx** [comment]
As @azoitl said, CIPster is a OpENer based fork, which follows a dual licensing scheme. As far as I am aware, CIPster does not have any Scanner capabilities, like OpENer.

For odva_ethernetip, this could be an example for a Scanner implementation, but is uses a completely different API as OpENer.

If there is a need for a Scanner application and there is support, I would be willing to start writing one. From my perspective I would still write it mainly from scratch, using OpENer itself as a base library and libevent or something similar for the communication handling.

**Comment by timoc** [comment]
The scanner is the other side of this protocol. Having one that works with OpENer would be the goal.

**Comment by CapXilinx** [comment]
OpENer works with a variety of Scanners (Rockwell PLC, Omron, CoDeSys ,ENIP), so getting a working scanner is not the point. Getting an open-source'ish (same license would have to apply for me) would be the benefit of this additional project.

**Comment by nefethael** [comment]
Hello all,

There is also https://github.com/nimbuscontrols/EIPScanner project, don't know if you already looked at it? 

Best regards,
Vincent

**Comment by CapXilinx** [comment]
Hi.

Thanks for bringing this to my attention, I didn't know about this project.

Best regards,
Martin
