### ISSUE TITLE
Added Ethernet Link object's counter attributes and GetAndClear service in preparation for DLR support

### ISSUE THREAD

**Issue by stm-at-esd** [EIPStackGroup/OpENer#276]
Hi,

I added an implementation for the Ethernet Link attribute number 4 "Interface Counters" and number 5 "Media Counters". Additionally this introduces the GetAndClear service for both of these attributes.

Because the retrieval of real hardware counters is highly dependent on the OS and the network driver (especially on embedded devices with non-standard drivers) I only provide here a dummy implementation to read these counters from the "hardware".

The implementation uses on object level the PreGetCallback to "read" the current counter values and update the object's counter members. The implementation uses on object level the PostGetCallback in the GetAndClear service to really "clear" the hardware counters after the current counter values have been encoded into the response.

These callbacks get connected to the Ethernet Link instances in the sampleapplication.c and are implemented in the new ethlinkcbs.c sources in the sample_application subdirectory of each port.

The dummy implementation of the counters serves test purposes and should make the Conformance Test happy. On each Get request each counter gets encoded the instance number, the attribute number, the member index of the counter in the appropriate CIP counter structure and the count of Get requests that already were received for that instance and attribute. This made it easy to check if the implementation of the Get service and the GetAndClear service transfer the right counter at the right position in the response.

Also the Conformance Test checks if the Media counters are really zero after a GetAndClear service.

I have a *.stc file for the OpENer with DLR support enabled but it is not included in the patch yet.
The question is where it should be put in the tree. 

Here come the patches:
[patches_191028.tar.gz](https://github.com/EIPStackGroup/OpENer/files/3784332/patches_191028.tar.gz)

Best regards,
    Stefan

**Comment by CapXilinx** [comment]
The STC file is put into the data folder. I would suggest OpENerDLR.stc as name

**Comment by CapXilinx** [comment]
Added in commit bad4d472c735d8a84ab4674a0b654cc0416c11e7
