### ISSUE TITLE
Cip Client

### ISSUE THREAD

**Issue by smccoorp** [EIPStackGroup/OpENer#277]
Can i use this stack for developing a cip client application.
I have a device which gives its connected sensors data on cip protocol. i want to develop application which can receive data from this device.
if this stack can't be used as cip client so can you please suggest other stack for the same in c language.

**Comment by CapXilinx** [comment]
Hi, this is a pure server stack. Please search the issues, this has been discussed already several times, and people suggested available stacks and programs.

Best
Martin
