### ISSUE TITLE
Compliance Test fails for Connection Manager / Unconnected Send

### ISSUE THREAD

**Issue by emb4fun** [EIPStackGroup/OpENer#31]
With issue #26 there was an updated implemented for "Unconnected Send" feature.
But this feature breaks the compliance test (CT). For the CT the new feature
"0x52 Unconnected_Send" was enabled too. And in this case the following errors occur:

STC File Error: Connection Manager Unconnected_Send supported and STC file does not indicate CIP routing support

STC indicates that Connection Manager Unconnected_Send service is implemented and test is unable to retrieve entry port. 'One instance of the Port object shall exist for each CIP routable port

It looks that the "CIP routing" and even the "Port" feature is needed for "Unconnected Send"?!

I think the patch from issue #26 should be removed.

**Comment by azoitl** [comment]
As the port object and also the routing is quite some effort and for adapter devices with a single port an overhead I would also recomend to remove the patch from isse #26.

**Comment by CapXilinx** [comment]
As suggested by azoitl and emb4fun the commit was reverted
