### ISSUE TITLE
Talos Security Advisory for EIP stack group OpENer ethernet/IP server 

### ISSUE THREAD

**Issue by CiscoTalos** [EIPStackGroup/OpENer#316]
Hello, the Cisco Talos team found a security vulnerability affecting EIP stack group OpENer ethernet/IP server. Since this is a public GitHub, please advise if this issue can be marked private before we submit the advisory with the details.

**Comment by CapXilinx** [comment]
Unfortunately, this is not possible as far as I know, but you can send me the details per email melik-merkumians@acin.tuwien.ac.at

Best regards,
Martin

**Comment by CiscoTalos** [comment]
Thanks, just sent email with the files directly to the email provided above.
