### ISSUE TITLE
OpENer for scanner

### ISSUE THREAD

**Issue by Vmrx45** [EIPStackGroup/OpENer#319]
Hi,

I know the question has already been asked but maybe it has changed with the last version. Is it possible now to do a EtherNet/IP scanner with OpENer stack ?

**Comment by CapXilinx** [comment]
Hi,

the answer is unfortunately still no. Currently, I am focusing on a CIP Security implementation.

**Comment by wgthompson** [comment]
Try this repo:
https://github.com/nimbuscontrols/EIPScanner
