### ISSUE TITLE
Implicit Messaging

### ISSUE THREAD

**Issue by AlexNov1** [EIPStackGroup/OpENer#320]
Hi everyone,

I try to exchange the implicit messages and use the EEIP.NET library and the EIPScan tool for this. Unfortunately I haven't succeeded so far and so I hope for your tips.

Here are the configurations I've tried so far:

EEIP:NET:
![image](https://user-images.githubusercontent.com/68536543/92579179-28f9ee00-f28d-11ea-84b7-fc76b8e87724.png)
Error: 'Connection failure, General Status Code: 1 Additional Status Code: 306 unknown'

EIPScan:
![image](https://user-images.githubusercontent.com/68536543/92579283-4dee6100-f28d-11ea-9520-efad7c28b8bc.png)

Does anyone have any idea what the problem is?

**Comment by CapXilinx** [comment]
Hi.

> Error: 'Connection failure, General Status Code: 1 Additional Status Code: 306 unknown

Your device is sending a Null Forward Open, which is not supported by OpENer currently. It seems not to respect the EDS file in this regard.

Best regards,
Martin

**Comment by CapXilinx** [comment]
Your EIPScan screenshot indicates, that the packages aren't reaching the OpENer device and are therefore unanswered

**Comment by AlexNov1** [comment]
Hi Martin,
thanks for your quick reply.

I don't use the EDS file and configure the communication manually, as can be seen on the screenshots.
I have just looked at the trace log, whether with EEIP.NET library or EIPScan the OpENer reports the same:

networkhandler: new TCP connection
>>> network handler: accepting new TCP socket: 3 
networkhandler: opened new TCP connection on fd 3
Entering HandleDataOnTcpSocket for socket: 3
Data received on tcp:
Handles data for TCP socket: 3
Register session
Adds socket 3 to socket timers
Sets time stamp for socket 3
Sets time stamp for socket 3
TCP reply sent:
Sets time stamp for socket 3
TCP response was not fully sent
Entering HandleDataOnTcpSocket for socket: 3
Data received on tcp:
Handles data for TCP socket: 3
Send Request/Reply Data
Sockaddr type id: 32769
NotifyMessageRouter: routing unconnected message
NotifyMessageRouter: calling notify function of class 'connection manager'
notify: found instance 1
notify: calling ForwardOpen service
ForwardOpen: ConConnID 2750872067, ProdConnID 2750875646, ConnSerNo 2046
We have a Null request
We have a Non-Matching request
Right now we cannot handle Null requests
AssembleForwardOpenResponse: sending error response
Sets time stamp for socket 3
TCP reply sent:
Sets time stamp for socket 3

Do you have any tip for configuring the communication so that no null forward open is sent?
I'm just getting started with implicit messaging and I really don't know how to do it :(

**Comment by CapXilinx** [comment]
That's up to the tool used. In principle, you do not need a null forward open for an implicit communication as all config data can be sent in a Non-Null Forward Open. The ENIPScanner tool for example sends no Null Forward Opens.

Null Forward Opens are used for pinging an ENIP device or to reconfigure a connection.

Best regards,
Martin

**Comment by AlexNov1** [comment]
My problem is that I don't know how to switch from null forward open to non null forward open. Or is it permanently set in the tools so that I have no control over it?
I did not find the ENIPScanner tool. Is it possible for you to add the link to that tool here?

**Comment by CapXilinx** [comment]
sorry, it is called ENIP Explorer https://sourceforge.net/projects/enipexplorer/

**Comment by CapXilinx** [comment]
I do not know the tools you are using, so I cannot really help you there.

**Comment by AlexNov1** [comment]
I have now loaded the Ethernet/IP Explorer (V1.2.0) and tried the implicit messaging with it. Unfortunately the result is the same as with my tools:
![image](https://user-images.githubusercontent.com/68536543/92887936-288c5f00-f415-11ea-8634-394d6a712149.png)

Wireshark also shows the same feedback from the OpENer for Ethernet/IP Explorer as with my tools:
![image](https://user-images.githubusercontent.com/68536543/92888626-c718c000-f415-11ea-9356-a832af7fcb97.png)

Do you know where the mistake could be?

I'm sorry that I'm taking so much time away from you, but I just don't know how else to get to the solution.

**Comment by CapXilinx** [comment]
Did you change anything on the OpENer code or config?
Sorry, I didn't had the time to try this myself

**Comment by AlexNov1** [comment]
I only fixed the bug I told you about in issue #314.
As of now I would have to debug to find out what is going wrong. If you have a tip where I can specifically check the code, it would be really great :)

**Comment by CapXilinx** [comment]
Just tested it, and everything works for me
![image](https://user-images.githubusercontent.com/5139573/93593379-4da04500-f9b4-11ea-8fc3-22029c61e257.png)

**Comment by CapXilinx** [comment]
As there is no further reaction to this issue, I close it now
