### ISSUE TITLE
OpENer CIP connection Timeout event is occurring rarely in 24 hours test

### ISSUE THREAD

**Issue by rakesh1225** [EIPStackGroup/OpENer#335]
Hello,

We are using OpENer stack version 2.1.0 on Linux for our development test.  We ran 24 hours CIP communication test between our device(Adapter - OpENer stack) and computer(Scanner). After a couple of hours Timeout event is observed from OpENer stack callback.  Can anyone let us know why this Timeout event occurs?
Note: Scanner is sending data periodically, however after sometime the adapter is throwing timeout after couple of hours.(RPI is 500ms). Scanner reconnects(using ForwardOpen)  after no response from adapter(for 500*4=2000ms).

**Comment by CapXilinx** [comment]
One thing which could be, is when the message number overflows. Do you have a wireshark trace of the relevant time period?

**Comment by rakesh1225** [comment]
Wireshark logs are attached for reference. xxx.30 is Adapter IP and xxx.35 is the Scanner IP. From the logs I understood that Scanner is keep sending messages periodically to the adapter, whereas Adapter stopped sending messages. This issue is intermittently observed in 24 hours test. Once the Adapter stopped sending messages, scanner initiates ForwardOpen requests and then the communication resumes. 
Not clear why the Timeout is triggered from the Adapter callbacks.
![post1](https://user-images.githubusercontent.com/3583648/108826314-29433700-75ea-11eb-9aa0-a1e543445cbc.jpg)
![post2](https://user-images.githubusercontent.com/3583648/108826324-2b0cfa80-75ea-11eb-8083-2048c0b66966.jpg)

**Comment by CapXilinx** [comment]
So, do I see this correct, you have 3 O->T connections and one T->O? Could you please tell me the connections configurations? (EO, IO, LO, etc.).
Perhaps the algorithm when the Timeout has to be reset has a corner-case error, if all sequence numbers connected to an assembly are equal.

**Comment by rakesh1225** [comment]
Yes, in this test I have 3 O->T connections and one T->O connection.

**Comment by rakesh1225** [comment]
O->T Connection: 0x4802
   Owner:Exclusive
   ConnectionType: Point To Point
  Priority: Scheduled(2)
Connection Size Type: Fixed
Connection Size: 2 bytes

T->O Connection: 0x29fa
   Owner:Exclusive
   ConnectionType: Multicast
  Priority: Scheduled(2)
Connection Size Type: Fixed
Connection Size: 506 bytes

**Comment by rakesh1225** [comment]
@CapXilinx , please let me know if any idea on the above issue
small info: we are using OpENer stack with commitID: 9181a4d9cc6f45fb04a4e396fbc0ae4c3337cfd1
https://github.com/EIPStackGroup/OpENer/commit/9181a4d9cc6f45fb04a4e396fbc0ae4c3337cfd1
