### ISSUE TITLE
Visual Studio project not working

### ISSUE THREAD

**Issue by Gaetanos-99** [EIPStackGroup/OpENer#350]
Hi everyone,

I'm trying to compile the project with WinGW according to "Compile for MinGW on Windows XP/7/8/10". The fifth step is unfortunately not working for me. I got the error message after trying to call "make":
<img width="664" alt="Unbenannt2" src="https://user-images.githubusercontent.com/81623053/137892894-be41227f-e9f6-4ab5-9d41-58df0db1741d.PNG">

Help would be highly appreciated. Thank you!

Greetings,
Gaetan

**Comment by CapXilinx** [comment]
Perhaps there is an issue with your path names? Not sure if CMake can handle all symbols

**Comment by CapXilinx** [comment]
Closed due to inactivity
