### ISSUE TITLE
How to connect and access my board to ab PLC using opener stack

### ISSUE THREAD

**Issue by varadharajanv** [EIPStackGroup/OpENer#37]
I've ported this code to TIVA c connected launchpad and also provided static IP address

My question is how to connect this to ab PLC 
And how to access this board from PLC lader logic
Require step by step procedure for connecting
I'm using ab compact logix 35e
And need procedure to include and access from PLC
Also how to create custom equipments 
Need complete procedure for using this code
I want to send data from PLC to my board

**Comment by CapXilinx** [comment]
You configure the OpENer device as any other EtherNet/IP device in your Rockwell software suite. On the other points I kindly ask you to look up your manual and the doxygen documentation of OpENer
