### ISSUE TITLE
Duplicate Symbols

### ISSUE THREAD

**Issue by MattBelanger321** [EIPStackGroup/OpENer#370]
When running make on the mingw sources there is a linker error.

![image](https://user-images.githubusercontent.com/39938415/162634381-0f40cbe7-b945-4db9-b449-e8ab724bddf2.png)

**Comment by CapXilinx** [comment]
Hi,
interestingly the build succeeds on Travis-CI, but also fails on my machine.
Could that be related to the version of GCC used? I am using 10.3. TDM-GCC (MinGW fork)

**Comment by CapXilinx** [comment]
ok, I mixed up where the extern declarations and the concrete global var definitions go. Seems this wasn't an issue until now
