### ISSUE TITLE
Are there any examples?

### ISSUE THREAD

**Issue by themightyoarfish** [EIPStackGroup/OpENer#406]
Does there exist any sample code for simple use cases such as polling an Ethernet/IP device?
I couldn't find anything instructive in the autogenerated doc.

**Comment by Suslsuk** [comment]
Is there a way to get a Visual Studio project to get started. For me as a pure Windows developer it is difficult to start with OpENer.

For example, it would be great to see sample code that other developers have used to implement an OpENer Implicit IO messaging adapter. 

Thanks

**Comment by azoitl** [comment]
The Cmake build system we are using allows to generate a VS project. I think this could help to get you started. The default example is already an Implicit IO messaging adapter.

**Comment by Suslsuk** [comment]
You are right, Cmake created the VS project. Thanks!

**Comment by nvienhuy** [comment]
Hi! How exactly do I create a VS project? Sorry but I am new and just trying to learn a thing or two, but could any one please instruct me on how to do that?

**Comment by nvienhuy** [comment]
Hi! How exactly do I create a VS project for the sample application? Sorry I am new and just trying to learn a thing or two, but could any one please instruct me on how to do that?

**Comment by azoitl** [comment]
Hi as pointed out above we are using CMake as make file and project generation tool. When you use CMake gui one of the first questions CMake will ask you what kind of project to generate. Here you can select visual studio and with that you should be set. For more info please refer to the CMake documentation.

**Comment by CapXilinx** [comment]
Closed, seems solved to me
