### ISSUE TITLE
Warning flag location

### ISSUE THREAD

**Issue by jvalenzuela** [EIPStackGroup/OpENer#419]
Regarding bf220454, should this warning instead be placed in the C flags defined in source/CMakeLists.txt, where the other warnings are configured?

**Comment by CapXilinx** [comment]
I moved it now so source, but I think it should be the other way round, as the warning settings are platform dependent.
This would then eliminate the need for the if in source

**Comment by jvalenzuela** [comment]
Understood. I initially thought the same, however, the mingw build also uses gcc.

**Comment by CapXilinx** [comment]
True, this is why I did it now this way :D
