### ISSUE TITLE
Need help connection points

### ISSUE THREAD

**Issue by Gilberto-BCM** [EIPStackGroup/OpENer#469]
Hi

I would like to understand the difference between different Connection Points that present in the OpEner sample application. So, Can someone give some further information on the this subject?

1) ExclusiveOwnerConnectionPoint
2) InputOnlyConnectionPoint
3) ListenOnlyConnectionPoint

BR
Gilberto

**Comment by CapXilinx** [comment]
Hi Gilbertio,

ad 1) the originator has exclusive access to write to the target device (e.g. in case of outputs or similar) and listens to certain inputs (reading values)
ad 2) the originator asks only to listen to a the targets inputs (reading values)
ad 3) as 2), but needs either a 1) or 2) connection to exist. If no ExO or InO connection exist, the connection will not be created. Also if the last ExO/InO is closed a LiO connection will be terminated.

BR
Martin
