### ISSUE TITLE
Transport Class question

### ISSUE THREAD

**Issue by wuhaibin001** [EIPStackGroup/OpENer#479]
cipioconnection.c file，SendConnectedData function，why use Sequenced Address Items if not Connection Class 0？《CIP Networks Library Volume 2：EtherNet/IP Adaptation of CIP》(Edition 1.21 April 2016)，in section 2-6.2.3, indicate that Sequenced Address Item shall be used for CIP transport class 0 and class 1 connected data.

**Comment by MartinMelikMerkumians** [comment]
April 2016 is quite dated, and section 2-6.2.3 does not exist in the current document. As the stack was part of a plugfest in 2019 and worked, I close this issue, as the question is outdated
