### ISSUE TITLE
cipconnectionmanager.c does not compile with logs

### ISSUE THREAD

**Issue by nefethael** [EIPStackGroup/OpENer#483]
In following line
https://github.com/EIPStackGroup/OpENer/blob/master/source/src/cip/cipconnectionmanager.c#L1593

Shouldn't we replace attribute_id by instance_id (or temp_instance_id)?

See https://github.com/EIPStackGroup/OpENer/commit/f59f486bb2c4713dc2ba5fe6064fde55f5630a97 changes

**Comment by CapXilinx** [comment]
I think you are right. Seems like I messed up this part of my merge conflict
