### ISSUE TITLE
The sample source code for the CIP master station?

### ISSUE THREAD

**Issue by bzyang** [EIPStackGroup/OpENer#69]
I am using the CIP protocol for data acquisition equipment, but I need a CIP master source. Can you provide the sample source code for the CIP master station?
Thanks

**Comment by pogojotz** [comment]
For a working quick-and-dirty-solution you can also look at the implementation of [Ethernet/IP Explorer](https://sourceforge.net/projects/enipexplorer/), if you don't mind it being written in C#.

**Comment by CapXilinx** [comment]
Currently OpENer is slave only. Altough I plan on expanding it, I have no exact schedule when I will be able to provide a Ethernet/IP master

Please see also https://github.com/EIPStackGroup/OpENer/issues/38
