### ISSUE TITLE
Building with Clang

### ISSUE THREAD

**Issue by simonlui** [EIPStackGroup/OpENer#78]
Is this explicitly supported? I got it working by changing the native compiler used with CMake gui and it worked (with warnings and whatnot), but was just wondering if you intend to support this or already do since I don't see anything about it in the Readme.

**Comment by CapXilinx** [comment]
I primarily use gcc and msvc compilers, but I intended to use scan-build for linting and style checking.

**Comment by simonlui** [comment]
Ah I see. Thanks for answering.
