### ISSUE TITLE
 v2.0 Release date 

### ISSUE THREAD

**Issue by rubensolozabal** [EIPStackGroup/OpENer#84]
Hi,

is still relase 2.0 in compliance with established deadlines (3 Feb 2017) ?

**Comment by CapXilinx** [comment]
Hi,

sorry, I will not hold the release date. Other responsibilities have kept me from working on the release, but the goal is to release 2.0 until end of February

**Comment by rubensolozabal** [comment]
thank you for answering so quickly"

**Comment by simonlui** [comment]
It's been about over two months. Is there any status update on a 2.0 release?
