### ISSUE TITLE
IApp_ functions remnants cleanup for OpENer 2.0?

### ISSUE THREAD

**Issue by simonlui** [EIPStackGroup/OpENer#90]
So since I had to work with the stable release of OpENer 1.12 for a while and then refactored my code based upon the trunk version since it can now connect with our PLC with the fix for #82, it seems like there still are some remnants of old IApp names internally inside OpENer.

> [slui@slui-mdworkpc src]$ack IApp
> ports/generic_networkhandler.c
> 236:void IApp_CloseSocket_udp(int socket_handle) {
> 240:void IApp_CloseSocket_tcp(int socket_handle) {
> 
> ports/generic_networkhandler.h
> 69:void IApp_CloseSocket_udp(int socket_handle);
> 71:void IApp_CloseSocket_tcp(int socket_handle);
> 
> cip/cipioconnection.c
> 406:  connection_object->remote_address.sin_addr.s_addr = 0; /* we don't know the address of the originate will be set in the IApp_CreateUDPSocket */
> 911:  IApp_CloseSocket_udp(
> 917:  IApp_CloseSocket_udp(
> 
> cip/cipassembly.h
> 37: *  the application will be informed with the IApp_after_assembly_data_received function.
> 
> cip/cipconnectionmanager.c
> 1499:    IApp_CloseSocket_udp(
> 1503:    IApp_CloseSocket_udp(
> 
> opener_api.h
> 278: * IApp_after_receive function.
> 
> enet_encap/encap.c
> 518:      IApp_CloseSocket_tcp(g_registered_sessions[i]);
> 670:      IApp_CloseSocket_tcp(socket);
> 681:      IApp_CloseSocket_tcp(g_registered_sessions[i]);

I'm not really one to decide on the design principles of the library, but it seems like these remaining functions should be renamed to be more consistent with the naming inside OpENer right now. This could probably be fixed when you go and fix #89, since it seems most of the remaining IApp functions deal with socket networking.

**Comment by CapXilinx** [comment]
Thanks for the hint. Seems like they slipped my naming convention change.
